use mylostcar;
insert into country values('ABW','ABW','Aruba','config',now(),null,null);
insert into country values('AFG','AFG','Afghanistan','config',now(),null,null);
insert into country values('AGO','AGO','Angola','config',now(),null,null);
insert into country values('AIA','AIA','Anguilla','config',now(),null,null);
insert into country values('ALB','ALB','Albania','config',now(),null,null);
insert into country values('AND','AND','Andorra','config',now(),null,null);
insert into country values('ANT','ANT','Netherlands Antilles','config',now(),null,null);
insert into country values('ARE','ARE','United Arab Emirates','config',now(),null,null);
insert into country values('ARG','ARG','Argentina','config',now(),null,null);
insert into country values('ARM','ARM','Armenia','config',now(),null,null);
insert into country values('ASM','ASM','American Samoa','config',now(),null,null);
insert into country values('ATA','ATA','Antarctica','config',now(),null,null);
insert into country values('ATF','ATF','French Southern territories','config',now(),null,null);
insert into country values('ATG','ATG','Antigua and Barbuda','config',now(),null,null);
insert into country values('AUS','AUS','Australia','config',now(),null,null);
insert into country values('AUT','AUT','Austria','config',now(),null,null);
insert into country values('AZE','AZE','Azerbaijan','config',now(),null,null);
insert into country values('BDI','BDI','Burundi','config',now(),null,null);
insert into country values('BEL','BEL','Belgium','config',now(),null,null);
insert into country values('BEN','BEN','Benin','config',now(),null,null);
insert into country values('BFA','BFA','Burkina Faso','config',now(),null,null);
insert into country values('BGD','BGD','Bangladesh','config',now(),null,null);
insert into country values('BGR','BGR','Bulgaria','config',now(),null,null);
insert into country values('BHR','BHR','Bahrain','config',now(),null,null);
insert into country values('BHS','BHS','Bahamas','config',now(),null,null);
insert into country values('BIH','BIH','Bosnia and Herzegovina','config',now(),null,null);
insert into country values('BLR','BLR','Belarus','config',now(),null,null);
insert into country values('BLZ','BLZ','Belize','config',now(),null,null);
insert into country values('BMU','BMU','Bermuda','config',now(),null,null);
insert into country values('BOL','BOL','Bolivia','config',now(),null,null);
insert into country values('BRA','BRA','Brazil','config',now(),null,null);
insert into country values('BRB','BRB','Barbados','config',now(),null,null);
insert into country values('BRN','BRN','Brunei','config',now(),null,null);
insert into country values('BTN','BTN','Bhutan','config',now(),null,null);
insert into country values('BVT','BVT','Bouvet Island','config',now(),null,null);
insert into country values('BWA','BWA','Botswana','config',now(),null,null);
insert into country values('CAF','CAF','Central African Republic','config',now(),null,null);
insert into country values('CAN','CAN','Canada','config',now(),null,null);
insert into country values('CCK','CCK','Cocos (Keeling) Islands','config',now(),null,null);
insert into country values('CHE','CHE','Switzerland','config',now(),null,null);
insert into country values('CHL','CHL','Chile','config',now(),null,null);
insert into country values('CHN','CHN','China','config',now(),null,null);
insert into country values('CIV','CIV','Côte dIvoire','config',now(),null,null);
insert into country values('CMR','CMR','Cameroon','config',now(),null,null);
insert into country values('COD','COD','Congo, The Democratic Republic of the','config',now(),null,null);
insert into country values('COG','COG','Congo','config',now(),null,null);
insert into country values('COK','COK','Cook Islands','config',now(),null,null);
insert into country values('COL','COL','Colombia','config',now(),null,null);
insert into country values('COM','COM','Comoros','config',now(),null,null);
insert into country values('CPV','CPV','Cape Verde','config',now(),null,null);
insert into country values('CRI','CRI','Costa Rica','config',now(),null,null);
insert into country values('CUB','CUB','Cuba','config',now(),null,null);
insert into country values('CXR','CXR','Christmas Island','config',now(),null,null);
insert into country values('CYM','CYM','Cayman Islands','config',now(),null,null);
insert into country values('CYP','CYP','Cyprus','config',now(),null,null);
insert into country values('CZE','CZE','Czech Republic','config',now(),null,null);
insert into country values('DEU','DEU','Germany','config',now(),null,null);
insert into country values('DJI','DJI','Djibouti','config',now(),null,null);
insert into country values('DMA','DMA','Dominica','config',now(),null,null);
insert into country values('DNK','DNK','Denmark','config',now(),null,null);
insert into country values('DOM','DOM','Dominican Republic','config',now(),null,null);
insert into country values('DZA','DZA','Algeria','config',now(),null,null);
insert into country values('ECU','ECU','Ecuador','config',now(),null,null);
insert into country values('EGY','EGY','Egypt','config',now(),null,null);
insert into country values('ERI','ERI','Eritrea','config',now(),null,null);
insert into country values('ESH','ESH','Western Sahara','config',now(),null,null);
insert into country values('ESP','ESP','Spain','config',now(),null,null);
insert into country values('EST','EST','Estonia','config',now(),null,null);
insert into country values('ETH','ETH','Ethiopia','config',now(),null,null);
insert into country values('FIN','FIN','Finland','config',now(),null,null);
insert into country values('FJI','FJI','Fiji Islands','config',now(),null,null);
insert into country values('FLK','FLK','Falkland Islands','config',now(),null,null);
insert into country values('FRA','FRA','France','config',now(),null,null);
insert into country values('FRO','FRO','Faroe Islands','config',now(),null,null);
insert into country values('FSM','FSM','Micronesia, Federated States of','config',now(),null,null);
insert into country values('GAB','GAB','Gabon','config',now(),null,null);
insert into country values('GBR','GBR','United Kingdom','config',now(),null,null);
insert into country values('GEO','GEO','Georgia','config',now(),null,null);
insert into country values('GHA','GHA','Ghana','config',now(),null,null);
insert into country values('GIB','GIB','Gibraltar','config',now(),null,null);
insert into country values('GIN','GIN','Guinea','config',now(),null,null);
insert into country values('GLP','GLP','Guadeloupe','config',now(),null,null);
insert into country values('GMB','GMB','Gambia','config',now(),null,null);
insert into country values('GNB','GNB','Guinea-Bissau','config',now(),null,null);
insert into country values('GNQ','GNQ','Equatorial Guinea','config',now(),null,null);
insert into country values('GRC','GRC','Greece','config',now(),null,null);
insert into country values('GRD','GRD','Grenada','config',now(),null,null);
insert into country values('GRL','GRL','Greenland','config',now(),null,null);
insert into country values('GTM','GTM','Guatemala','config',now(),null,null);
insert into country values('GUF','GUF','French Guiana','config',now(),null,null);
insert into country values('GUM','GUM','Guam','config',now(),null,null);
insert into country values('GUY','GUY','Guyana','config',now(),null,null);
insert into country values('HKG','HKG','Hong Kong','config',now(),null,null);
insert into country values('HMD','HMD','Heard Island and McDonald Islands','config',now(),null,null);
insert into country values('HND','HND','Honduras','config',now(),null,null);
insert into country values('HRV','HRV','Croatia','config',now(),null,null);
insert into country values('HTI','HTI','Haiti','config',now(),null,null);
insert into country values('HUN','HUN','Hungary','config',now(),null,null);
insert into country values('IDN','IDN','Indonesia','config',now(),null,null);
insert into country values('IND','IND','India','config',now(),null,null);
insert into country values('IOT','IOT','British Indian Ocean Territory','config',now(),null,null);
insert into country values('IRL','IRL','Ireland','config',now(),null,null);
insert into country values('IRN','IRN','Iran','config',now(),null,null);
insert into country values('IRQ','IRQ','Iraq','config',now(),null,null);
insert into country values('ISL','ISL','Iceland','config',now(),null,null);
insert into country values('ISR','ISR','Israel','config',now(),null,null);
insert into country values('ITA','ITA','Italy','config',now(),null,null);
insert into country values('JAM','JAM','Jamaica','config',now(),null,null);
insert into country values('JOR','JOR','Jordan','config',now(),null,null);
insert into country values('JPN','JPN','Japan','config',now(),null,null);
insert into country values('KAZ','KAZ','Kazakstan','config',now(),null,null);
insert into country values('KEN','KEN','Kenya','config',now(),null,null);
insert into country values('KGZ','KGZ','Kyrgyzstan','config',now(),null,null);
insert into country values('KHM','KHM','Cambodia','config',now(),null,null);
insert into country values('KIR','KIR','Kiribati','config',now(),null,null);
insert into country values('KNA','KNA','Saint Kitts and Nevis','config',now(),null,null);
insert into country values('KOR','KOR','South Korea','config',now(),null,null);
insert into country values('KWT','KWT','Kuwait','config',now(),null,null);
insert into country values('LAO','LAO','Laos','config',now(),null,null);
insert into country values('LBN','LBN','Lebanon','config',now(),null,null);
insert into country values('LBR','LBR','Liberia','config',now(),null,null);
insert into country values('LBY','LBY','Libyan Arab Jamahiriya','config',now(),null,null);
insert into country values('LCA','LCA','Saint Lucia','config',now(),null,null);
insert into country values('LIE','LIE','Liechtenstein','config',now(),null,null);
insert into country values('LKA','LKA','Sri Lanka','config',now(),null,null);
insert into country values('LSO','LSO','Lesotho','config',now(),null,null);
insert into country values('LTU','LTU','Lithuania','config',now(),null,null);
insert into country values('LUX','LUX','Luxembourg','config',now(),null,null);
insert into country values('LVA','LVA','Latvia','config',now(),null,null);
insert into country values('MAC','MAC','Macao','config',now(),null,null);
insert into country values('MAR','MAR','Morocco','config',now(),null,null);
insert into country values('MCO','MCO','Monaco','config',now(),null,null);
insert into country values('MDA','MDA','Moldova','config',now(),null,null);
insert into country values('MDG','MDG','Madagascar','config',now(),null,null);
insert into country values('MDV','MDV','Maldives','config',now(),null,null);
insert into country values('MEX','MEX','Mexico','config',now(),null,null);
insert into country values('MHL','MHL','Marshall Islands','config',now(),null,null);
insert into country values('MKD','MKD','Macedonia','config',now(),null,null);
insert into country values('MLI','MLI','Mali','config',now(),null,null);
insert into country values('MLT','MLT','Malta','config',now(),null,null);
insert into country values('MMR','MMR','Myanmar','config',now(),null,null);
insert into country values('MNG','MNG','Mongolia','config',now(),null,null);
insert into country values('MNP','MNP','Northern Mariana Islands','config',now(),null,null);
insert into country values('MOZ','MOZ','Mozambique','config',now(),null,null);
insert into country values('MRT','MRT','Mauritania','config',now(),null,null);
insert into country values('MSR','MSR','Montserrat','config',now(),null,null);
insert into country values('MTQ','MTQ','Martinique','config',now(),null,null);
insert into country values('MUS','MUS','Mauritius','config',now(),null,null);
insert into country values('MWI','MWI','Malawi','config',now(),null,null);
insert into country values('MYS','MYS','Malaysia','config',now(),null,null);
insert into country values('MYT','MYT','Mayotte','config',now(),null,null);
insert into country values('NAM','NAM','Namibia','config',now(),null,null);
insert into country values('NCL','NCL','New Caledonia','config',now(),null,null);
insert into country values('NER','NER','Niger','config',now(),null,null);
insert into country values('NFK','NFK','Norfolk Island','config',now(),null,null);
insert into country values('NGA','NGA','Nigeria','config',now(),null,null);
insert into country values('NIC','NIC','Nicaragua','config',now(),null,null);
insert into country values('NIU','NIU','Niue','config',now(),null,null);
insert into country values('NLD','NLD','Netherlands','config',now(),null,null);
insert into country values('NOR','NOR','Norway','config',now(),null,null);
insert into country values('NPL','NPL','Nepal','config',now(),null,null);
insert into country values('NRU','NRU','Nauru','config',now(),null,null);
insert into country values('NZL','NZL','New Zealand','config',now(),null,null);
insert into country values('OMN','OMN','Oman','config',now(),null,null);
insert into country values('PAK','PAK','Pakistan','config',now(),null,null);
insert into country values('PAN','PAN','Panama','config',now(),null,null);
insert into country values('PCN','PCN','Pitcairn','config',now(),null,null);
insert into country values('PER','PER','Peru','config',now(),null,null);
insert into country values('PHL','PHL','Philippines','config',now(),null,null);
insert into country values('PLW','PLW','Palau','config',now(),null,null);
insert into country values('PNG','PNG','Papua New Guinea','config',now(),null,null);
insert into country values('POL','POL','Poland','config',now(),null,null);
insert into country values('PRI','PRI','Puerto Rico','config',now(),null,null);
insert into country values('PRK','PRK','North Korea','config',now(),null,null);
insert into country values('PRT','PRT','Portugal','config',now(),null,null);
insert into country values('PRY','PRY','Paraguay','config',now(),null,null);
insert into country values('PSE','PSE','Palestine','config',now(),null,null);
insert into country values('PYF','PYF','French Polynesia','config',now(),null,null);
insert into country values('QAT','QAT','Qatar','config',now(),null,null);
insert into country values('REU','REU','Réunion','config',now(),null,null);
insert into country values('ROM','ROM','Romania','config',now(),null,null);
insert into country values('RUS','RUS','Russian Federation','config',now(),null,null);
insert into country values('RWA','RWA','Rwanda','config',now(),null,null);
insert into country values('SAU','SAU','Saudi Arabia','config',now(),null,null);
insert into country values('SDN','SDN','Sudan','config',now(),null,null);
insert into country values('SEN','SEN','Senegal','config',now(),null,null);
insert into country values('SGP','SGP','Singapore','config',now(),null,null);
insert into country values('SGS','SGS','South Georgia and the South Sandwich Islands','config',now(),null,null);
insert into country values('SHN','SHN','Saint Helena','config',now(),null,null);
insert into country values('SJM','SJM','Svalbard and Jan Mayen','config',now(),null,null);
insert into country values('SLB','SLB','Solomon Islands','config',now(),null,null);
insert into country values('SLE','SLE','Sierra Leone','config',now(),null,null);
insert into country values('SLV','SLV','El Salvador','config',now(),null,null);
insert into country values('SMR','SMR','San Marino','config',now(),null,null);
insert into country values('SOM','SOM','Somalia','config',now(),null,null);
insert into country values('SPM','SPM','Saint Pierre and Miquelon','config',now(),null,null);
insert into country values('STP','STP','Sao Tome and Principe','config',now(),null,null);
insert into country values('SUR','SUR','Suriname','config',now(),null,null);
insert into country values('SVK','SVK','Slovakia','config',now(),null,null);
insert into country values('SVN','SVN','Slovenia','config',now(),null,null);
insert into country values('SWE','SWE','Sweden','config',now(),null,null);
insert into country values('SWZ','SWZ','Swaziland','config',now(),null,null);
insert into country values('SYC','SYC','Seychelles','config',now(),null,null);
insert into country values('SYR','SYR','Syria','config',now(),null,null);
insert into country values('TCA','TCA','Turks and Caicos Islands','config',now(),null,null);
insert into country values('TCD','TCD','Chad','config',now(),null,null);
insert into country values('TGO','TGO','Togo','config',now(),null,null);
insert into country values('THA','THA','Thailand','config',now(),null,null);
insert into country values('TJK','TJK','Tajikistan','config',now(),null,null);
insert into country values('TKL','TKL','Tokelau','config',now(),null,null);
insert into country values('TKM','TKM','Turkmenistan','config',now(),null,null);
insert into country values('TMP','TMP','East Timor','config',now(),null,null);
insert into country values('TON','TON','Tonga','config',now(),null,null);
insert into country values('TTO','TTO','Trinidad and Tobago','config',now(),null,null);
insert into country values('TUN','TUN','Tunisia','config',now(),null,null);
insert into country values('TUR','TUR','Turkey','config',now(),null,null);
insert into country values('TUV','TUV','Tuvalu','config',now(),null,null);
insert into country values('TWN','TWN','Taiwan','config',now(),null,null);
insert into country values('TZA','TZA','Tanzania','config',now(),null,null);
insert into country values('UGA','UGA','Uganda','config',now(),null,null);
insert into country values('UKR','UKR','Ukraine','config',now(),null,null);
insert into country values('UMI','UMI','United States Minor Outlying Islands','config',now(),null,null);
insert into country values('URY','URY','Uruguay','config',now(),null,null);
insert into country values('USA','USA','United States','config',now(),null,null);
insert into country values('UZB','UZB','Uzbekistan','config',now(),null,null);
insert into country values('VAT','VAT','Holy See (Vatican City State)','config',now(),null,null);
insert into country values('VCT','VCT','Saint Vincent and the Grenadines','config',now(),null,null);
insert into country values('VEN','VEN','Venezuela','config',now(),null,null);
insert into country values('VGB','VGB','Virgin Islands, British','config',now(),null,null);
insert into country values('VIR','VIR','Virgin Islands, U.S.','config',now(),null,null);
insert into country values('VNM','VNM','Vietnam','config',now(),null,null);
insert into country values('VUT','VUT','Vanuatu','config',now(),null,null);
insert into country values('WLF','WLF','Wallis and Futuna','config',now(),null,null);
insert into country values('WSM','WSM','Samoa','config',now(),null,null);
insert into country values('YEM','YEM','Yemen','config',now(),null,null);
insert into country values('YUG','YUG','Yugoslavia','config',now(),null,null);
insert into country values('ZAF','ZAF','South Africa','config',now(),null,null);
insert into country values('ZMB','ZMB','Zambia','config',now(),null,null);
insert into country values('ZWE','ZWE','Zimbabwe','config',now(),null,null);
