package com.stolenvehicle.constants;

public enum AuditEnum {

	LOGIN, REGISTER, LOGOUT, ACTIVATE_USER, CHANGE_PASSWORD, UPDATE_PROFILE, RESET_PASSWORD, SET_PASSWORD, UPLOAD_ATTACHMENT_FOR_THEFT, UPDATE_FIND_STATUS;
}
